<a href="https://colab.research.google.com/github/Chaitanyate/Deep_learning/blob/master/NewFeed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torchvision
from torchvision.datasets import MNIST
import torchvision.transforms as transform

In [0]:
datasets=MNIST(root='home/',download=True,transform=transform.ToTensor())

In [17]:
import numpy as np
len(datasets)

60000

In [0]:

def split_ind(n,val):
  nval=int(val*n)
  idx=np.random.permutation(n)
  return idx[nval:],idx[:nval]
  

In [0]:
train,validate=split_ind(len(datasets),0.2)

In [0]:
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.data.dataloader import DataLoader 

In [0]:
batch_size=100
train_sample=SubsetRandomSampler(train)
train_loads=DataLoader(datasets,batch_size,sampler=train_sample)

In [0]:
val_sample=SubsetRandomSampler(validate)
val_loads=DataLoader(datasets,batch_size,sampler=val_sample)

In [0]:
import torch.nn as nn
input_size=784
output_size=10
hidden_size=32
import torch.nn.functional as F
use_cuda=torch.cuda.is_available()
#devices=torch.device('cuda:0' if use_cuda else 'cpu')

In [0]:
class mnist(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super(mnist,self).__init__()
    self.linear1=nn.Linear(input_size,hidden_size)
    self.linear2=nn.Linear(hidden_size,output_size)
    #self.relu=nn.Relu().cuda(devices)

  def forward(self,xb):
      xb=xb.reshape(-1,784)
      out=self.linear1(xb)
      out=F.relu(out)
      out=self.linear2(out)
      return out

In [0]:
model=mnist(input_size,hidden_size,output_size)


In [73]:
for i,j in train_loads:
  print(j)
  print(i)
  out=model(i)
  break
print((out)[:2].data)


tensor([0, 6, 9, 3, 6, 5, 9, 7, 5, 7, 4, 3, 4, 9, 1, 6, 8, 0, 6, 7, 1, 8, 1, 2,
        4, 4, 0, 7, 3, 8, 3, 1, 5, 1, 9, 0, 7, 4, 1, 2, 1, 0, 4, 2, 9, 3, 0, 6,
        2, 9, 2, 4, 7, 0, 8, 3, 1, 3, 7, 0, 8, 2, 8, 3, 1, 5, 1, 3, 1, 4, 2, 3,
        8, 1, 3, 9, 4, 9, 5, 2, 2, 9, 8, 6, 9, 6, 0, 8, 7, 4, 5, 7, 4, 2, 8, 0,
        8, 6, 1, 6])
tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 

In [64]:
for t in model.parameters():
  print(t.shape)

torch.Size([32, 784])
torch.Size([32])
torch.Size([10, 32])
torch.Size([10])


In [65]:
def get_default_devices():
  if torch.cuda.is_available():
    return torch.device('cuda')
  else:
    return torch.device('cpu')

device=get_default_devices()
device

device(type='cuda')

In [0]:
def to_Device(data,device):
  if isinstance(data,(list,tuple)):
    return [to_Device(x,device) for x in data]


  return data.to(device,non_blocking=True)

In [30]:

for images,label in train_loads:
  images=to_Device(images,device)
  print(images,device)
  break


tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0.

In [0]:
class DeviceDataLoader():
  def __init__(self,dl,device):
    self.dl=dl
    self.device=device

  def __iter__(self):
    for b in self.dl:
      yield to_Device(b,self.device)

  def __len__(self):
    return len(self.dl)

In [0]:
train_dl=DeviceDataLoader(train_loads,device)
val_dl=DeviceDataLoader(val_loads,device)

In [33]:
for xb,yb in val_dl:
  print(xb.device)
  print(yb)
  break

cuda:0
tensor([7, 7, 3, 5, 3, 3, 7, 4, 3, 1, 2, 8, 4, 2, 3, 8, 6, 6, 6, 3, 3, 7, 6, 5,
        7, 2, 4, 9, 6, 1, 9, 1, 5, 8, 4, 2, 5, 9, 7, 3, 7, 6, 0, 4, 2, 9, 6, 9,
        3, 7, 6, 6, 4, 6, 1, 4, 0, 3, 9, 1, 2, 8, 5, 4, 7, 5, 1, 0, 2, 2, 8, 5,
        5, 0, 8, 2, 8, 7, 3, 9, 9, 6, 7, 2, 9, 4, 1, 8, 1, 2, 3, 2, 0, 8, 8, 6,
        7, 9, 6, 1], device='cuda:0')


In [0]:
def loss_batch(model,loss_func,xb,yb,opt=None,metric=None):
  preds=model(xb)
  loss=loss_func(preds,yb)

  if opt is not None:
    loss.backward()
    opt.stop()
    opt.zero()

    metric_result=None
    if metric is not None:
      metric_result=metric(preds,yb)

    return loss.item(),len(xb),metric_result



In [0]:
def evaluate(model,loss_fun,valid_dl,metric):
  with torch.no_grad():
    results=[loss_batch(model,loss_fun,xb,yb,metric=metric) for xb,yb in valid_dl]
    losses,nums,metrics=zip(*results)
    total=np.sum(nums)
    avg_loss=np.sum(np.multiply(losses,num))/total
    avg_metric=np.sum(np.multiply(metrics,num))/total

    return avg_metric,avg_loss,total
    

In [0]:
def accuracy(outputs,labels):
  _,preds=torch.max(output,dim=1)
  return torch.sum(preds==label)/len(label)



In [0]:
def fit(epochs,lr,model,loss_fn,train_dl,valid_dl,metric=None,opt_fn=None):
  losses,metrices=[],[]

  if opt_fn is None:opt_fn=torch.optim.SGD
  opt=torch.optim.SGD(model.parameters(),lr=lr)

  for epoch in range(epochs):
    for xb,yb in train_dl:
      loss=loss_batch(model,loss_fn,xb,yb,opt)
    result=evaluate(model,loss_fn,valid_dl,metric,val_loss,total,val_metric=results)

    losses.append(val_loss)
    metrices.append(val+val_metric)

    if metric is None:
      print('Epochs[{}/{}].Loss:{:.4f}'.format(epochs+1,epochs,val_loss))

    else:
      print('Epochs[{}/{}].Loss:{:.4f}'.format(epochs+1,epochs,val_loss,metric.__name__,val_metric))

    return losses,metrices


In [45]:
model=mnist(input_size,hidden_size,output_size)
to_Device(model,device)

mnist(
  (linear1): Linear(in_features=784, out_features=32, bias=True)
  (linear2): Linear(in_features=32, out_features=10, bias=True)
)

In [48]:
val_loss,total,val_acc=evaluate(model,F.cross_entropy,val_loads,metric=accuracy)
print("loss:{:.4f},accuracy:{:.4f}".format(val_loss,val_acc))


RuntimeError: ignored

In [0]:
losses1,metrices1=fit(5,0.5,model,F.cross_entropy,train_dl,val_dl,accuracy)